app/routes.py
#!/usr/bin/python3
"""Define API routes"""
from flask import Flask, flash, Blueprint, request, jsonify, render_template, redirect, url_for, session, current_app
from .models import db, Post, User, Comment, Like, Tip, Challenge
from sqlalchemy.orm import joinedload
from flask_login import LoginManager, login_user, logout_user, current_user, login_required
from .email_verify import send_confirmation_email, confirm_token
import logging

api = Blueprint('api', __name__, template_folder='templates')
logging.basicConfig(level=logging.DEBUG)


@api.route('/')
def index():
    """Render the pre-log page"""
    return render_template('index.html')


@api.route('/register', methods=['GET', 'POST'])
def show_register_form():
    """"Handle user registration and Render the registr form"""
    if request.method == 'POST':
        data = request.form
        existing_user = User.query.filter_by(username=data['username']).first()
        if existing_user:
            flash('Username already taken. Please choose a different one.', 'error')
            return redirect(url_for('api.show_register_form'))

        existing_email = User.query.filter_by(email=data['email']).first()
        if existing_email:
            flash('Email already registered. Please use a different email.', 'error')
            return redirect(url_for('api.show_register_form'))

        new_user = User(username=data['username'], email=data['email'], password=data['password'])
        new_user.set_password(data['password'])
        db.session.add(new_user)
        db.session.commit()
        send_confirmation_email(new_user.email)
        flash('A confirmation email has been sent via email. Please check your inbox and spam folder.', 'info')
        return redirect(url_for('api.show_login_form'))
    return render_template('register.html')

@api.route('/confirm/<token>')
def confirm_email(token):
    """Confirm user's email using the token"""
    try:
        email = confirm_token(token)
    except:
        flash('The confirmation link is invalid or has expired.', 'danger')
        return redirect(url_for('api.show_login_form'))

    user = User.query.filter_by(email=email).first_or_404()
    if user.email_confirmed:
        flash('Account already confirmed. Please login.', 'success')
    else:
        user.email_confirmed = True
        db.session.commit()
        flash('You have confirmed your account. Thanks!', 'success')
    return redirect(url_for('api.show_login_form'))


@api.route('/login', methods=['GET', 'POST'])
def show_login_form():
    """Render the login form"""
    if current_user.is_authenticated:
        return redirect(url_for('api.home'))
    
    if request.method == 'POST':
        data = request.form
        user = User.query.filter_by(email=data['email']).first()
        if user and user.verify_password(data['password']):
            if not user.email_confirmed:
                flash('Please confirm your email to login.', 'error')
                return redirect(url_for('api.show_login_form'))
            
            login_user(user)
            flash('Login successful!', 'success')
            return redirect(url_for('api.home'))
        else:
            flash('Invalid credentials!', 'error')
    
    return render_template('login.html')


@api.route('/logout')
@login_required
def logout():
    """Logout the user"""
    logout_user()
    flash('You have been logged out.', 'info')
    return redirect(url_for('api.show_login_form'))


@api.route('/home')
@login_required
def home():
    """Render the post-log:home page with posts and daily tip"""
    daily_tip = Tip.query.order_by(Tip.created_at.desc()).first()
    recent_posts = Post.query.order_by(Post.created_at.desc()).limit(5).all()
    posts_with_likes = Post.query.options(joinedload(Post.likes)).all()
    sorted_posts = sorted(posts_with_likes, key=lambda post: post.count_likes(), reverse=True)
    popular_posts = sorted_posts[:5]
    all_posts = Post.query.order_by(Post.created_at.desc()).all()
    
    return render_template('home.html', 
                           daily_tip=daily_tip,
                           recent_posts=recent_posts,
                           popular_posts=popular_posts,
                           all_posts=all_posts)


@api.route('/allposts')
@login_required
def all_posts():
    """Render the all-posts page"""
    all_posts = Post.query.order_by(Post.created_at.desc()).all()
    return render_template('all_posts.html', posts=all_posts)


@api.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    """Render the user profile page"""
    user = User.query.get(current_user.id)
    if request.method == 'POST':
        data = request.form
        user.username = data.get('username', user.username)
        user.email = data.get('email', user.email)
        user.bio = data.get('bio', user.bio)
        user.profile_picture = data.get('profile_picture', user.profile_picture)
        db.session.commit()
        flash('Profile updated successfully', 'success')
        return redirect(url_for('api.profile'))
    return render_template('profile.html', user=user)


@api.route('/user/<username>')
@login_required
def view_user_profile(username):
    """Handles view of users profile through herf"""
    user = User.query.filter_by(username=username).first_or_404()
    return render_template('profile.html', user=user, view_only=True)


@api.route('/writing_zone', methods=['GET'])
@login_required
def dashboard():
    """Render the writingzone page with user posts and daily challenge"""
    user_posts = Post.query.filter_by(user_id=current_user.id).all()
    posts_data = [{'id': post.id, 'title': post.title, 'image_url': post.image_url} for post in user_posts]
    daily_challenge = Challenge.query.order_by(Challenge.created_at.desc()).first()

    return render_template('dashboard.html', posts_data=posts_data, daily_challenge=daily_challenge)


@api.route('/posts/<int:post_id>', methods=['GET'])
@login_required
def get_post(post_id):
    """Render the post page to view post with certain id"""
    post = Post.query.options(joinedload(Post.author)).get_or_404(post_id)
    return render_template('post.html', post=post)


@api.route('/create_post', methods=['GET', 'POST'])
@login_required
def create_post():
    """Render the create new post page"""
    if request.method == 'POST':
        data = request.form
        new_post = Post(title=data['title'], content=data['content'], image_url=data['image_url'], user_id=current_user.id)
        try:
            db.session.add(new_post)
            db.session.commit()
            flash('Post created successfully!', 'success')
            return redirect(url_for('api.dashboard'))
        except Exception as e:
            db.session.rollback()
            flash(f'Error creating post: {str(e)}', 'error')
            return redirect(url_for('api.create_post'))

    return render_template('createpost.html')


@api.route('/update_post/<int:post_id>', methods=['POST'])
@login_required
def update_post(post_id):
    """Render the edit-post page"""
    data = request.form
    post = Post.query.get(post_id)
    if not post:
        flash('Post not found.', 'error')
        return redirect(url_for('api.dashboard'))

    post.title = data.get('title', post.title)
    post.content = data.get('content', post.content)
    post.image_url = data.get('image_url', post.image_url)
    db.session.commit()
    flash('Post updated successfully.', 'success')
    return redirect(url_for('api.get_post', post_id=post_id))


@api.route('/posts/<int:post_id>', methods=['DELETE'])
@login_required
def delete_post(post_id):
    """Handle delete post"""
    post = Post.query.get_or_404(post_id)
    if post.user_id != current_user.id:
        return jsonify({'error': 'Unauthorized'}), 403

    db.session.delete(post)
    db.session.commit()
    flash('Post deleted successfully.', 'success')
    return jsonify({'message': 'Post deleted'}), 200


@api.route('/posts/<int:post_id>/like', methods=['POST'])
@login_required
def like_post(post_id):
    """Handle like/unlike feature"""
    post = Post.query.get_or_404(post_id)
    user_id = current_user.id
    like = Like.query.filter_by(post_id=post_id, user_id=user_id).first()
    
    if like:
        db.session.delete(like)
        db.session.commit()
        liked = False
    else:
        new_like = Like(post_id=post_id, user_id=user_id)
        db.session.add(new_like)
        db.session.commit()
        liked = True

    likes = Like.query.filter_by(post_id=post_id).all()
    liked_users = [{'username': like.user.username} for like in likes]

    return jsonify({'liked': liked, 'likes_count': post.count_likes(), 'liked_users': liked_users})


@api.route('/posts/<post_id>/comments', methods=['GET'])
def get_comments(post_id):
    """Display comments for post"""
    comments = Comment.query.filter_by(post_id=post_id).all()
    return jsonify([comment.to_dict() for comment in comments]), 200


@api.route('/posts/<int:post_id>/comments', methods=['POST'])
@login_required
def create_comment(post_id):
    """Handle creation of a new comment"""
    data = request.json
    current_app.logger.debug(f'Received data: {data}')
    content = data.get('content')
    if not content:
        return jsonify({'message': 'Comment content is required.'}), 400

    user_id = current_user.id

    comment = Comment(content=content, user_id=user_id, post_id=post_id)
    db.session.add(comment)
    db.session.commit()
    flash('Comment updated successfully.', 'success')

    user = User.query.get(user_id)

    return jsonify({'id': comment.id, 'content': comment.content, 'user': {'username': user.username}}), 201


@api.route('/comments/<int:comment_id>', methods=['PUT'])
@login_required
def update_comment(comment_id):
    """Handle comment edit"""
    data = request.json
    content = data.get('content')

    comment = Comment.query.get(comment_id)
    if comment:
        comment.content = content

app/templates/all_posts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>All Posts - YouCanWrite</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lobster&family=Julius+Sans+One&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='images/favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='images/favicon-16x16.png') }}">
</head>
<body class="bg-gray-100" style="display: flex; flex-direction: column; min-height: 100vh;">
    <div class="flex flex-col flex-grow">
        <nav class="shadow-lg py-1 px-4">
            <div class="container mx-auto flex justify-between items-center">
                <a href="{{ url_for('api.home') }}" class="text-2xl font-bold flex items-center">
                    <img src="{{ url_for('static', filename='images/LOGO.PNG') }}" alt="Logo" class="h-16 w-16">
                    <div class="flex flex-col">
                    <h1 class="text-2xl font-bold">YouCanWrite</h1>
                    <p class="text-sm">FROM SPARK TO MASTERPIECE</p>
                </div>
                </a>
                <div class="menu">
                    <a href="{{ url_for('api.home') }}" class="mx-2">Home</a>
                    <a href="{{ url_for('api.dashboard') }}" class="mx-2">WritingZone</a>
                    <a href="{{ url_for('api.profile') }}" class="mx-2">Profile</a>
                    <a href="{{ url_for('api.logout') }}" class="mx-2">Logout</a>
                </div>
            </div>
        </nav>
        <div class="container mx-auto mt-10 mb-4 flex flex-wrap">
            <h2 class="text-2xl font-bold mb-4 w-full">All Posts</h2>
            {% for post in posts %}
            <div class="w-full md:w-1/2 lg:w-1/3 p-2">
                <div class="bg-white p-4 rounded-lg shadow-lg">
                    <a href="{{ url_for('api.get_post', post_id=post.id) }}">
                        <img src="{{ post.image_url if post.image_url else url_for('static', filename='images/post_img.png') }}" alt="{{ post.title }}" class="w-full h-48 object-cover rounded mb-4">
                        <h3 class="text-xl font-bold">{{ post.title }}</h3>
                    </a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <footer class="text-center py-4 mt-auto w-full">
        &copy; 2024 YouCanWrite. All rights reserved.
    </footer>
</body>
</html>

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Your App{% endblock %}</title>
</head>
<body>
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            <div class="flash-messages">
                {% for category, message in messages %}
                    <div class="flash-message {{ category }}">
                        <span>{{ message }}</span>
                        <button class="close-button">&times;</button>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    {% endwith %}

    {% block content %}{% endblock %}
    <script src="{{ url_for('static', filename='js/flash.js') }}"></script>
</body>
</html>

app/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home - YouCanWrite</title>
    {% extends "base.html" %}
    {% block title %}Home{% endblock %}
    {% block content %}
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lobster&family=Julius+Sans+One&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='images/favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='images/favicon-16x16.png') }}">
</head>
<body class="bg-gray-100" style="display: flex; flex-direction: column; min-height: 100vh;">
    <div class="flex flex-col flex-grow">
        <nav class="shadow-lg py-1 px-4">
            <div class="container mx-auto flex justify-between items-center">
                <a href="{{ url_for('api.home') }}" class="text-2xl font-bold flex items-center">
                    <img src="{{ url_for('static', filename='images/LOGO.PNG') }}" alt="Logo" class="h-16 w-16">
                    <div class="flex flex-col">
                    <h1 class="text-2xl font-bold">YouCanWrite</h1>
                    <p class="text-sm">FROM SPARK TO MASTERPIECE</p>
                </div>
                </a>
                <div class="menu">
                    <a href="{{ url_for('api.home') }}" class="mx-2">Home</a>
                    <a href="{{ url_for('api.dashboard') }}" class="mx-2">WritingZone</a>
                    <a href="{{ url_for('api.profile') }}" class="mx-2">Profile</a>
                    <a href="{{ url_for('api.logout') }}" class="mx-2">Logout</a>
                </div>
            </div>
        </nav>
    <div class="container mx-auto mt-10 mb-4 flex" style="flex: 1;">
        <div class="w-1/4 bg-white p-4 rounded-lg shadow-md h-full">
            <h2 class="text-2xl font-bold mb-4">Writing Tip</h2>
            <p class="text-left text-gray-700 mb-6">.{{ daily_tip.tip }}</p>
            <a href="{{ url_for('api.get_tips') }}" class="text-purple-700 hover:underline" style="font-weight: 600; text-decoration: none; color: #6f42c1; background-color: #f5f5f5; padding: 8px 12px; border-radius: 4px; display: inline-block; transition: background-color 0.2s ease-in-out;">Explore more</a>
        </div>
        <div class="w-3/4 ml-4">         
            <div class="bg-white p-4 rounded-lg shadow-md mb-4 flex items-center justify-between">
                <h2 class="text-2xl font-bold mr-4">Ready for daily challenge?</h2>
                <a href="{{ url_for('api.dashboard') }}" class="px-4 py-2 bg-purple-700 text-white rounded-lg hover:bg-purple-800">Let's go!</a>
            </div>
            <div class="mt-4 mb-2 flex justify-end">
                <a href="{{ url_for('api.all_posts') }}" class="px-4 py-2 bg-purple-700 text-white rounded-lg hover:bg-purple-800">View All Posts</a>
            </div>   
            <div class="grid grid-cols-2 gap-4">
                <div class="bg-white p-4 rounded-lg shadow-md" id="recentPostsContainer">
                    <h2 class="text-2xl font-bold mb-2 ">Recently Added</h2>
                    {% for post in recent_posts %}
                <div class="bg-white p-4 rounded-lg shadow-lg mb-4">
                    <a href="{{ url_for('api.get_post', post_id=post.id) }}">
                        <img src="{{ post.image_url if post.image_url else url_for('static', filename='images/post_img.png') }}" alt="{{ post.title }}" class="w-full h-48 object-cover rounded mb-4">
                        <h3 class="text-xl font-bold">{{ post.title }}</h3>
                    </a>
                </div>
                {% endfor %}
                </div>
                <div class="bg-white p-4 rounded-lg shadow-md" id="popularPostsContainer">
                    <h2 class="text-2xl font-bold mb-2">Most Populer</h2>
                    {% for post in popular_posts %}
                    <div class="bg-white p-4 rounded-lg shadow-lg mb-4">
                        <a href="{{ url_for('api.get_post', post_id=post.id) }}">
                            <img src="{{ post.image_url if post.image_url else url_for('static', filename='images/post_img.png') }}" alt="{{ post.title }}" class="w-full h-48 object-cover rounded mb-4">
                            <h3 class="text-xl font-bold">{{ post.title }}</h3>
                        </a>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <footer class="py-4 mt-auto w-full">
        &copy; 2024 YouCanWrite. All rights reserved..
    </footer>
{% endblock %}
</body>
</html>

app/templates/post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ post.title }} - YouCanWrite</title>
    {% extends "base.html" %}
    {% block title %}Post{% endblock %}
    {% block content %}
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='images/favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='images/favicon-16x16.png') }}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.2.0/highlight.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/quill@2.0.2/dist/quill.snow.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/quill@2.0.2/dist/quill.js"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/poststyle.css') }}">
</head>
<body class="bg-gray-100" style="display: flex; flex-direction: column; min-height: 100vh;">
    <div class="flex flex-col flex-grow">
        <nav class="shadow-lg py-1 px-4">
            <div class="container mx-auto flex justify-between items-center">
                <a href="{{ url_for('api.home') }}" class="text-2xl font-bold flex items-center">
                    <img src="{{ url_for('static', filename='images/LOGO.PNG') }}" alt="Logo" class="h-16 w-16">
                    <div class="flex flex-col">
                    <h1 class="text-2xl font-bold">YouCanWrite</h1>
                    <p class="text-sm">FROM SPARK TO MASTERPIECE</p>
                </div>
                </a>
                <div class="menu">
                    <a href="{{ url_for('api.home') }}" class="mx-2">Home</a>
                    <a href="{{ url_for('api.dashboard') }}" class="mx-2">WritingZone</a>
                    <a href="{{ url_for('api.profile') }}" class="mx-2">Profile</a>
                    <a href="{{ url_for('api.logout') }}" class="mx-2">Logout</a>
                </div>
            </div>
        </nav>
    <main class="container mx-auto p-4 flex-grow">
        <div id="postDisplay" class="bg-white p-6 rounded-lg shadow-lg max-w-full">
            <img id="postImg" src="{{ post.image_url if post.image_url else url_for('static', filename='images/post_img.png') }}" alt="{{ post.title }}" class="w-full h-64 object-cover rounded mb-4" style="width: 1440px; height: 480px; object-fit: cover;">
            <h2 class="text-3xl font-bold mb-2" style="font-family: 'Lobster', cursive; color: #4b0082; text-align: center;" >{{ post.title }}</h2>
            <p class="text-left text-gray-600 mb-4" style="font-family: 'Julius Sans One', sans-serif; color: #000000;">Author: <a href="{{ url_for('api.view_user_profile', username=post.author.username) }}" id="postAuthorName" class="text-blue-500 hover:text-blue-600">{{ post.author.username }}</a></p>
            <div class="text-left text-lg text-black mb-4 post-container">{{ post.content | safe }}</div>
            <div class="flex justify-between items-center mb-4">
                <div class="flex gap-2" data-post-id="{{ post.id }}">
                    <button class="like-btn py-1.5 px-3 hover:text-purple-600 hover:scale-105 hover:shadow text-center border border-gray-300 rounded-md border-gray-400 h-8 text-sm flex items-left gap-1 lg:gap-2">
                        <svg class="w-4 h-4" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M6.633 10.5c.806 0 1.533-.446 2.031-1.08a9.041 9.041 0 012.861-2.4c.723-.384 1.35-.956 1.653-1.715a4.498 4.498 0 00.322-1.672V3a.75.75 0 01.75-.75A2.25 2.25 0 0116.5 4.5c0 1.152-.26 2.243-.723 3.218-.266.558.107 1.282.725 1.282h3.126c1.026 0 1.945.694 2.054 1.715.045.422.068.85.068 1.285a11.95 11.95 0 01-2.649 7.521c-.388.482-.987.729-1.605.729H13.48c-.483 0-.964-.078-1.423-.23l-3.114-1.04a4.501 4.501 0 00-1.423-.23H5.904M14.25 9h2.25M5.904 18.75c.083.205.173.405.27.602.197.4-.078.898-.523.898h-.908c-.889 0-1.713-.518-1.972-1.368a12 12 0 01-.521-3.507c0-1.553.295-3.036.831-4.398C3.387 10.203 4.167 9.75 5 9.75h1.053c.472 0 .745.556.5.96a8.958 8.958 0 00-1.302 4.665c0 1.194.232 2.333.654 3.375z"></path>
                        </svg>
                        <span class="like-count">{{ post.likes|length }}</span>
                    </button>
                    <p class="text-sm text-gray-800 text-left mb-4 inline">
                        <ul class="liked-users inline">
                            {% for like in post.likes %}
                                <li class="inline">
                                    <a href="{{ url_for('api.view_user_profile', username=like.user.username) }}" class="text-purple-900 hover:text-blue-600" style="font-family: 'Raleway', sans-serif;">{{ like.user.username }}</a>
                                    {% if not loop.last %}, {% endif %}
                                </li>
                            {% endfor %}
                        </ul>
                    </p>
                </div>                     
                {% if current_user.id == post.author.id %}
                <div>
                    <button class="bg-purple-500 text-white py-2 px-4 rounded hover:bg-purple-700 mr-2" style="font-family: 'Raleway', sans-serif;" onclick="toggleEdit(true)">Edit</button>
                    <button class="bg-red-500 text-white py-2 px-4 rounded hover:bg-red-700" style="font-family: 'Raleway', sans-serif;" onclick="deletePost('{{ post.id }}')">Delete</button>
                </div>
                {% endif %}
            </div>
            <h3 class="text-2xl font-bold mb-4" style="font-family: 'Raleway', sans-serif;">Comments</h3>
            <div id="comments" class="mb-4" style="font-family: 'Raleway', sans-serif;">
                <ul>
                    {% for comment in post.comments %}
                    <li class="mb-4">
                        <div id="comment-{{ comment.id }}">
                            <div id="commentDisplay-{{ comment.id }}">
                                <p class="text-left text-lg text-gray-800 mb-2">{{ comment.content }}</p>
                                <p class="text-sm text-gray-800 text-left mb-2">Comment by: <a href="{{ url_for('api.view_user_profile', username=comment.user.username) }}" id="commentAuthorName" class="text-purple-900 hover:text-blue-600">{{ comment.user.username }}</a></p>
                                <p class="text-xs text-gray-600 text-left">{{ comment.created_at }}</p>
                                {% if current_user.id == comment.user.id %}
                                <div class="flex items-center mt-2">
                                    <button class="bg-purple-500 text-white py-1 px-3 rounded hover:bg-purple-700 mr-2" style="font-family: 'Raleway', sans-serif;" onclick="editComment('{{ comment.id }}')">Edit</button>
                                    <button class="bg-red-500 text-white py-1 px-3 rounded hover:bg-red-700" style="font-family: 'Raleway', sans-serif;" onclick="deleteComment('{{ comment.id }}', '{{ post.id }}')">Delete</button>
                                </div>
                                {% endif %}
                            </div>
                            <div id="commentEditForm-{{ comment.id }}" style="display: none;">
                                <textarea id="commentEditInput-{{ comment.id }}" class="w-full p-2 border border-gray-300 rounded-lg" rows="2">{{ comment.content }}</textarea>
                                <button class="bg-purple-500 text-white py-1 px-3 rounded hover:bg-purple-700 mr-2" style="font-family: 'Raleway', sans-serif;" onclick="updateComment('{{ comment.id }}')">Save</button>
                                <button class="bg-gray-500 text-white py-1 px-3 rounded hover:bg-gray-700" style="font-family: 'Raleway', sans-serif;" onclick="toggleCommentEdit('{{ comment.id }}', false)">Cancel</button>
                            </div>
                        </div>
                    </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="bg-gray-200 p-4 rounded-lg mb-4">
                <textarea id="commentInput" class="w-full p-2 border border-gray-300 rounded-lg" rows="3" placeholder="Add a comment..."></textarea>
                <button id="submitComment" class="bg-purple-500 text-white py-2 px-4 rounded hover:bg-purple-700 mt-2" style="font-family: 'Raleway', sans-serif;"onclick="submitComment('{{ post.id }}')">Submit</button>
            </div>
        </div>
        <div id="postEditForm" class="container mx-auto mt-8" style="display: none;">
            <div class="p-4 bg-white rounded shadow">
                <h1 class="text-3xl font-bold mb-4" style="font-family: 'Raleway', sans-serif; font-weight: 300; line-height: 1.6; color: #000000;">Edit Post</h1>
                <form action="{{ url_for('api.update_post', post_id=post.id) }}" method="POST">
                    <div class="mb-4">
                        <label for="title" class="block text-gray-700" style="font-family: 'Raleway', sans-serif;">Title</label>
                        <input type="text" name="title" id="title" value="{{ post.title }}" class="w-full px-4 py-2 border rounded">
                    </div>
                    <div class="mb-4" id="content">{{ post.content | safe }}</div>
                    <input type="text" name="content" hidden />
                    <div class="mb-4">
                        <label for="image_url" class="block text-gray-700" style="font-family: 'Raleway', sans-serif;">Post Image URL</label>
                        <input type="text" name="image_url" id="image_url" value="{{ post.image_url if post.image_url else url_for('static', filename='images/post_img.png') }}" class="w-full px-4 py-2 border rounded" oninput="updatePostImage(this.value)">
                    </div>
                    <div class="flex justify-between">
                        <button type="button" onclick="toggleEdit(false)" class="bg-gray-500 text-white px-4 py-2 rounded" style="font-family: 'Raleway', sans-serif;">Cancel</button>
                        <button type="submit" class="bg-purple-500 text-white px-4 py-2 rounded" style="font-family: 'Raleway', sans-serif;">Save</button>
                    </div>
                </form>
            </div>
        </div>
    </main>
    <footer class="text-center py-4 mt-auto w-full">
        &copy; 2024 YouCanWrite. All rights reserved.
    </footer>
    <script src="{{ url_for('static', filename='js/post.js') }}"></script>
    <script>
        const Font = Quill.import('formats/font');
        const Align = Quill.import('formats/align');
        const Size = Quill.import('formats/size');

        Font.whitelist = ['mirza', 'roboto', 'raleway', 'tajawal', 'noto-kufi-arabic', 'scheherazade'];
        Size.whitelist = ['small', 'normal', 'large', 'huge'];

        Quill.register(Font, true);
        Quill.register(Align, true);
        Quill.register(Size, true);

        const toolbarOptions = [
        [{ 'font': Font.whitelist }],
        [{ 'size': Size.whitelist }],
        ['bold', 'italic', 'underline', 'strike'],
        [{ 'color': [] }, { 'background': [] }],
        [{ 'align': [] },],
        ['clean']
    ];
    
        // Initialize QuillJS editor
        const quill = new Quill('#content', {
            theme: 'snow',
            modules: {
                syntax: true, 
                toolbar: toolbarOptions,
            }
        });
        quill.on('text-change', function() {
            const content = document.querySelector('input[name="content"]');
            content.value = quill.root.innerHTML;
        });
    </script>
    </body>
    {% endblock %}
    </html>    